imagenet_classnames = [{'en': 'tench', 'ja': 'テンチ'},
 {'en': 'goldfish', 'ja': '金魚'},
 {'en': 'great white shark', 'ja': 'ホホジロザメ'},
 {'en': 'tiger shark', 'ja': 'イタチザメ'},
 {'en': 'hammerhead shark', 'ja': 'ハンマーヘッド'},
 {'en': 'electric ray', 'ja': 'シビレエイ'},
 {'en': 'stingray', 'ja': 'アカエイ'},
 {'en': 'rooster', 'ja': 'コック'},
 {'en': 'hen', 'ja': 'めんどり'},
 {'en': 'ostrich', 'ja': 'ダチョウ'},
 {'en': 'brambling', 'ja': 'アトリ'},
 {'en': 'goldfinch', 'ja': 'ゴシキヒワ'},
 {'en': 'house finch', 'ja': 'ハウスフィンチ'},
 {'en': 'junco', 'ja': 'ユキヒメドリ'},
 {'en': 'indigo bunting', 'ja': 'インディゴホオジロ'},
 {'en': 'American robin', 'ja': 'ロビン'},
 {'en': 'bulbul', 'ja': 'ブルブル'},
 {'en': 'jay', 'ja': 'カケス'},
 {'en': 'magpie', 'ja': 'カササギ'},
 {'en': 'chickadee', 'ja': '四十雀'},
 {'en': 'American dipper', 'ja': '水クロウタドリ'},
 {'en': 'kite (bird of prey)', 'ja': '凧'},
 {'en': 'bald eagle', 'ja': '白頭ワシ'},
 {'en': 'vulture', 'ja': 'ハゲワシ'},
 {'en': 'great grey owl', 'ja': 'カラフトフクロウ'},
 {'en': 'fire salamander', 'ja': '欧州ファイアサラマンダー'},
 {'en': 'smooth newt', 'ja': '共通イモリ'},
 {'en': 'newt', 'ja': 'イモリ'},
 {'en': 'spotted salamander', 'ja': 'サンショウウオを発見'},
 {'en': 'axolotl', 'ja': 'アホロートル'},
 {'en': 'American bullfrog', 'ja': 'ウシガエル'},
 {'en': 'tree frog', 'ja': 'アマガエル'},
 {'en': 'tailed frog', 'ja': 'つかれたカエル'},
 {'en': 'loggerhead sea turtle', 'ja': 'とんちき'},
 {'en': 'leatherback sea turtle', 'ja': 'オサガメ'},
 {'en': 'mud turtle', 'ja': '鼈'},
 {'en': 'terrapin', 'ja': 'テラピン'},
 {'en': 'box turtle', 'ja': 'ハコガメ'},
 {'en': 'banded gecko', 'ja': '縞模様のヤモリ'},
 {'en': 'green iguana', 'ja': '共通イグアナ'},
 {'en': 'Carolina anole', 'ja': 'アメリカンカメレオン'},
 {'en': 'desert grassland whiptail lizard', 'ja': 'ウィッペイル'},
 {'en': 'agama', 'ja': 'アガマトカゲ'},
 {'en': 'frilled-necked lizard', 'ja': 'フリルトカゲ'},
 {'en': 'alligator lizard', 'ja': 'アリゲータートカゲ'},
 {'en': 'Gila monster', 'ja': 'アメリカドクトカゲ'},
 {'en': 'European green lizard', 'ja': '緑のトカゲ'},
 {'en': 'chameleon', 'ja': 'アフリカのカメレオン'},
 {'en': 'Komodo dragon', 'ja': 'コモドドラゴン'},
 {'en': 'Nile crocodile', 'ja': 'アフリカのワニ'},
 {'en': 'American alligator', 'ja': 'アメリカワニ'},
 {'en': 'triceratops', 'ja': 'トリケラトプス'},
 {'en': 'worm snake', 'ja': '雷のヘビ'},
 {'en': 'ring-necked snake', 'ja': 'リングネックスネーク'},
 {'en': 'eastern hog-nosed snake', 'ja': 'ホーノースヘビ'},
 {'en': 'smooth green snake', 'ja': '緑のヘビ'},
 {'en': 'kingsnake', 'ja': 'キングスネーク'},
 {'en': 'garter snake', 'ja': 'ガータースネーク'},
 {'en': 'water snake', 'ja': '水蛇'},
 {'en': 'vine snake', 'ja': 'つるヘビ'},
 {'en': 'night snake', 'ja': '夜のヘビ'},
 {'en': 'boa constrictor', 'ja': 'ボア・コンストリクター'},
 {'en': 'African rock python', 'ja': 'ロックパイソン'},
 {'en': 'Indian cobra', 'ja': 'インドコブラ'},
 {'en': 'green mamba', 'ja': 'グリーンマンバ'},
 {'en': 'sea snake', 'ja': 'ウミヘビ'},
 {'en': 'Saharan horned viper', 'ja': 'ツノクサリヘビ'},
 {'en': 'eastern diamondback rattlesnake', 'ja': 'ダイヤ'},
 {'en': 'sidewinder rattlesnake', 'ja': 'サイドワインダー'},
 {'en': 'trilobite', 'ja': '三葉虫'},
 {'en': 'harvestman', 'ja': '刈り入れ作業者'},
 {'en': 'scorpion', 'ja': 'サソリ'},
 {'en': 'yellow garden spider', 'ja': '黒と金の庭クモ'},
 {'en': 'barn spider', 'ja': '納屋クモ'},
 {'en': 'European garden spider', 'ja': '庭クモ'},
 {'en': 'southern black widow', 'ja': 'クロゴケグモ'},
 {'en': 'tarantula', 'ja': 'タランチュラ'},
 {'en': 'wolf spider', 'ja': 'オオカミのクモ'},
 {'en': 'tick', 'ja': 'ダニ'},
 {'en': 'centipede', 'ja': '百足'},
 {'en': 'black grouse', 'ja': 'クロライチョウ'},
 {'en': 'ptarmigan', 'ja': '雷鳥'},
 {'en': 'ruffed grouse', 'ja': 'ひだえりの付いたライチョウ'},
 {'en': 'prairie grouse', 'ja': '草原チキン'},
 {'en': 'peafowl', 'ja': '孔雀'},
 {'en': 'quail', 'ja': 'ウズラ'},
 {'en': 'partridge', 'ja': 'ヤマウズラ'},
 {'en': 'african grey parrot', 'ja': 'アフリカの灰色'},
 {'en': 'macaw', 'ja': 'コンゴウインコ'},
 {'en': 'sulphur-crested cockatoo', 'ja': '硫黄トキオウム'},
 {'en': 'lorikeet', 'ja': 'インコ'},
 {'en': 'coucal', 'ja': 'バンケン'},
 {'en': 'bee eater', 'ja': '蜂食べる人'},
 {'en': 'hornbill', 'ja': 'サイチョウ'},
 {'en': 'hummingbird', 'ja': 'ハチドリ'},
 {'en': 'jacamar', 'ja': '錐嘴'},
 {'en': 'toucan', 'ja': 'オオハシ'},
 {'en': 'duck', 'ja': 'ドレイク'},
 {'en': 'red-breasted merganser', 'ja': '赤ブレストアイサ属のガモ'},
 {'en': 'goose', 'ja': 'ガチョウ'},
 {'en': 'black swan', 'ja': '黒い白鳥'},
 {'en': 'tusker', 'ja': 'タスカービール'},
 {'en': 'echidna', 'ja': 'ハリモグラ'},
 {'en': 'platypus', 'ja': 'カモノハシ'},
 {'en': 'wallaby', 'ja': 'ワラビー'},
 {'en': 'koala', 'ja': 'コアラ'},
 {'en': 'wombat', 'ja': 'ウォンバット'},
 {'en': 'jellyfish', 'ja': 'クラゲ'},
 {'en': 'sea anemone', 'ja': 'イソギンチャク'},
 {'en': 'brain coral', 'ja': '脳サンゴ'},
 {'en': 'flatworm', 'ja': '扁形動物'},
 {'en': 'nematode', 'ja': '線虫'},
 {'en': 'conch', 'ja': '巻き貝'},
 {'en': 'snail', 'ja': 'カタツムリ'},
 {'en': 'slug', 'ja': 'ナメクジ'},
 {'en': 'sea slug', 'ja': 'ウミウシ'},
 {'en': 'chiton', 'ja': 'キトン'},
 {'en': 'chambered nautilus', 'ja': 'オウムガイ'},
 {'en': 'Dungeness crab', 'ja': 'アメリカイチョウガニ'},
 {'en': 'rock crab', 'ja': '岩カニ'},
 {'en': 'fiddler crab', 'ja': 'シオマネキ'},
 {'en': 'red king crab', 'ja': 'タラバガニ'},
 {'en': 'American lobster', 'ja': 'アメリカンロブスター'},
 {'en': 'spiny lobster', 'ja': '伊勢エビ'},
 {'en': 'crayfish', 'ja': 'ザリガニ'},
 {'en': 'hermit crab', 'ja': 'ヤドカリ'},
 {'en': 'isopod', 'ja': '等脚類'},
 {'en': 'white stork', 'ja': 'コウノトリ'},
 {'en': 'black stork', 'ja': 'ナベコウ'},
 {'en': 'spoonbill', 'ja': 'ヘラサギ'},
 {'en': 'flamingo', 'ja': 'フラミンゴ'},
 {'en': 'little blue heron', 'ja': '小さな青いサギ'},
 {'en': 'great egret', 'ja': 'アメリカン白鷺'},
 {'en': 'bittern bird', 'ja': 'にがり'},
 {'en': 'crane bird', 'ja': 'クレーン'},
 {'en': 'limpkin', 'ja': 'ツルモドキ科の鳥'},
 {'en': 'common gallinule', 'ja': 'ヨーロピアン水鳥'},
 {'en': 'American coot', 'ja': 'アメリカオオバン'},
 {'en': 'bustard', 'ja': 'ノガン'},
 {'en': 'ruddy turnstone', 'ja': 'キョウジョシギ'},
 {'en': 'dunlin', 'ja': '赤担保シギ'},
 {'en': 'common redshank', 'ja': 'アカアシシギ'},
 {'en': 'dowitcher', 'ja': 'オオハシシギ'},
 {'en': 'oystercatcher', 'ja': 'ミヤコドリ'},
 {'en': 'pelican', 'ja': 'ペリカン'},
 {'en': 'king penguin', 'ja': 'キングペンギン'},
 {'en': 'albatross', 'ja': 'アルバトロス'},
 {'en': 'grey whale', 'ja': 'コククジラ'},
 {'en': 'killer whale', 'ja': 'シャチ'},
 {'en': 'dugong', 'ja': 'ジュゴン'},
 {'en': 'sea lion', 'ja': 'アシカ'},
 {'en': 'Chihuahua', 'ja': 'チワワ'},
 {'en': 'Japanese Chin', 'ja': '狆'},
 {'en': 'Maltese', 'ja': 'マルチーズ犬'},
 {'en': 'Pekingese', 'ja': '狆'},
 {'en': 'Shih Tzu', 'ja': 'シーズー、シーズー'},
 {'en': 'King Charles Spaniel', 'ja': 'ブレナムスパニエル'},
 {'en': 'Papillon', 'ja': 'パピヨン'},
 {'en': 'toy terrier', 'ja': 'トイテリア'},
 {'en': 'Rhodesian Ridgeback', 'ja': 'ローデシアン・リッジバック'},
 {'en': 'Afghan Hound', 'ja': 'アフガンハウンド'},
 {'en': 'Basset Hound', 'ja': 'バセット犬'},
 {'en': 'Beagle', 'ja': 'ビーグル'},
 {'en': 'Bloodhound', 'ja': 'ブラッドハウンド'},
 {'en': 'Bluetick Coonhound', 'ja': 'ブルーティック'},
 {'en': 'Black and Tan Coonhound', 'ja': '黒と黄褐色の猟犬'},
 {'en': 'Treeing Walker Coonhound', 'ja': 'ウォーカーハウンド'},
 {'en': 'English foxhound', 'ja': 'イングリッシュフォックスハウンド'},
 {'en': 'Redbone Coonhound', 'ja': 'レッドボーン'},
 {'en': 'borzoi', 'ja': 'ボルゾイ'},
 {'en': 'Irish Wolfhound', 'ja': 'アイリッシュ・ウルフハウンド'},
 {'en': 'Italian Greyhound', 'ja': 'イタリアングレーハウンド'},
 {'en': 'Whippet', 'ja': 'ウィペット'},
 {'en': 'Ibizan Hound', 'ja': 'イビサハウンド'},
 {'en': 'Norwegian Elkhound', 'ja': 'ノルウェーエルクハウンド'},
 {'en': 'Otterhound', 'ja': 'オッターハウンド'},
 {'en': 'Saluki', 'ja': 'サルーキ'},
 {'en': 'Scottish Deerhound', 'ja': 'スコティッシュ・ディアハウンド'},
 {'en': 'Weimaraner', 'ja': 'ワイマラナー'},
 {'en': 'Staffordshire Bull Terrier', 'ja': 'スタフォードシャーブルテリア'},
 {'en': 'American Staffordshire Terrier', 'ja': 'アメリカン・スタッフォードシャー・テリア'},
 {'en': 'Bedlington Terrier', 'ja': 'ベドリントンテリア'},
 {'en': 'Border Terrier', 'ja': 'ボーダーテリア'},
 {'en': 'Kerry Blue Terrier', 'ja': 'ケリーブルーテリア'},
 {'en': 'Irish Terrier', 'ja': 'アイリッシュテリア'},
 {'en': 'Norfolk Terrier', 'ja': 'ノーフォークテリア'},
 {'en': 'Norwich Terrier', 'ja': 'ノーリッチ・テリア'},
 {'en': 'Yorkshire Terrier', 'ja': 'ヨークシャーテリア'},
 {'en': 'Wire Fox Terrier', 'ja': 'ワイヤーヘアー・フォックステリア'},
 {'en': 'Lakeland Terrier', 'ja': 'レークランドテリア'},
 {'en': 'Sealyham Terrier', 'ja': 'シーリーハムテリア'},
 {'en': 'Airedale Terrier', 'ja': 'エアデール'},
 {'en': 'Cairn Terrier', 'ja': 'ケルン'},
 {'en': 'Australian Terrier', 'ja': 'オーストラリアテリア'},
 {'en': 'Dandie Dinmont Terrier', 'ja': 'ダンディディンモントテリア'},
 {'en': 'Boston Terrier', 'ja': 'ボストンブル'},
 {'en': 'Miniature Schnauzer', 'ja': 'ミニチュアシュナウザー'},
 {'en': 'Giant Schnauzer', 'ja': 'ジャイアントシュナウザー'},
 {'en': 'Standard Schnauzer', 'ja': 'スタンダードシュナウザー'},
 {'en': 'Scottish Terrier', 'ja': 'スコッチテリア'},
 {'en': 'Tibetan Terrier', 'ja': 'チベタンテリア'},
 {'en': 'Australian Silky Terrier', 'ja': 'シルキーテリア'},
 {'en': 'Soft-coated Wheaten Terrier', 'ja': 'ソフトコーテッド・ウィートン・テリア'},
 {'en': 'West Highland White Terrier', 'ja': 'ウェストハイランドホワイトテリア'},
 {'en': 'Lhasa Apso', 'ja': 'ラサ'},
 {'en': 'Flat-Coated Retriever', 'ja': 'フラットコーテッド・レトリーバー'},
 {'en': 'Curly-coated Retriever', 'ja': 'カーリーコーティングされたレトリーバー'},
 {'en': 'Golden Retriever', 'ja': 'ゴールデンレトリバー'},
 {'en': 'Labrador Retriever', 'ja': 'ラブラドル・レトリーバー犬'},
 {'en': 'Chesapeake Bay Retriever', 'ja': 'チェサピーク湾レトリーバー'},
 {'en': 'German Shorthaired Pointer', 'ja': 'ジャーマン・ショートヘア・ポインタ'},
 {'en': 'Vizsla', 'ja': 'ビズラ'},
 {'en': 'English Setter', 'ja': 'イングリッシュセッター'},
 {'en': 'Irish Setter', 'ja': 'アイリッシュセッター'},
 {'en': 'Gordon Setter', 'ja': 'ゴードンセッター'},
 {'en': 'Brittany dog', 'ja': 'ブリタニースパニエル'},
 {'en': 'Clumber Spaniel', 'ja': 'クランバー'},
 {'en': 'English Springer Spaniel', 'ja': 'イングリッシュスプリンガー'},
 {'en': 'Welsh Springer Spaniel', 'ja': 'ウェルシュスプリンガースパニエル'},
 {'en': 'Cocker Spaniel', 'ja': 'コッカースパニエル'},
 {'en': 'Sussex Spaniel', 'ja': 'サセックススパニエル'},
 {'en': 'Irish Water Spaniel', 'ja': 'アイルランドのウォータースパニエル'},
 {'en': 'Kuvasz', 'ja': 'クバース犬'},
 {'en': 'Schipperke', 'ja': 'スキッパーキー'},
 {'en': 'Groenendael dog', 'ja': 'ベルジアン・シェパード・ドッグ・グローネンダール'},
 {'en': 'Malinois', 'ja': 'マリノア'},
 {'en': 'Briard', 'ja': 'ブリアール'},
 {'en': 'Australian Kelpie', 'ja': 'ケルピー'},
 {'en': 'Komondor', 'ja': 'コモンドール'},
 {'en': 'Old English Sheepdog', 'ja': 'オールドイングリッシュシープドッグ'},
 {'en': 'Shetland Sheepdog', 'ja': 'シェトランドシープドッグ'},
 {'en': 'collie', 'ja': 'コリー'},
 {'en': 'Border Collie', 'ja': 'ボーダーコリー'},
 {'en': 'Bouvier des Flandres dog', 'ja': 'ブーヴィエ・デ・フランドル'},
 {'en': 'Rottweiler', 'ja': 'ロットワイラー'},
 {'en': 'German Shepherd Dog', 'ja': 'ジャーマンシェパード'},
 {'en': 'Dobermann', 'ja': 'ドーベルマン犬'},
 {'en': 'Miniature Pinscher', 'ja': 'ミニチュアピンシャー'},
 {'en': 'Greater Swiss Mountain Dog', 'ja': 'グレータースイスマウンテンドッグ'},
 {'en': 'Bernese Mountain Dog', 'ja': 'バーネーズマウンテンドッグ'},
 {'en': 'Appenzeller Sennenhund', 'ja': 'アッペンツェル'},
 {'en': 'Entlebucher Sennenhund', 'ja': 'エントレブッシャー'},
 {'en': 'Boxer', 'ja': 'ボクサー'},
 {'en': 'Bullmastiff', 'ja': 'ブルマスチフ'},
 {'en': 'Tibetan Mastiff', 'ja': 'チベットマスチフ'},
 {'en': 'French Bulldog', 'ja': 'フレンチブルドッグ'},
 {'en': 'Great Dane', 'ja': 'グレートデーン'},
 {'en': 'St. Bernard', 'ja': 'セントバーナード'},
 {'en': 'husky', 'ja': 'エスキモー犬'},
 {'en': 'Alaskan Malamute', 'ja': 'マラミュート'},
 {'en': 'Siberian Husky', 'ja': 'シベリアンハスキー'},
 {'en': 'Dalmatian', 'ja': 'ダルメシアン'},
 {'en': 'Affenpinscher', 'ja': 'アーフェンピンシャー'},
 {'en': 'Basenji', 'ja': 'バセンジー'},
 {'en': 'pug', 'ja': 'パグ'},
 {'en': 'Leonberger', 'ja': 'レオンバーグ'},
 {'en': 'Newfoundland dog', 'ja': 'ニューファンドランド島'},
 {'en': 'Great Pyrenees dog', 'ja': 'グレートピレニーズ'},
 {'en': 'Samoyed', 'ja': 'サモエド'},
 {'en': 'Pomeranian', 'ja': 'ポメラニアン'},
 {'en': 'Chow Chow', 'ja': 'チャウ'},
 {'en': 'Keeshond', 'ja': 'キースホンド'},
 {'en': 'brussels griffon', 'ja': 'ブラバンソングリフォン'},
 {'en': 'Pembroke Welsh Corgi', 'ja': 'ペンブローク'},
 {'en': 'Cardigan Welsh Corgi', 'ja': 'カーディガン'},
 {'en': 'Toy Poodle', 'ja': 'トイプードル'},
 {'en': 'Miniature Poodle', 'ja': 'ミニチュアプードル'},
 {'en': 'Standard Poodle', 'ja': 'スタンダードプードル'},
 {'en': 'Mexican hairless dog (xoloitzcuintli)', 'ja': 'メキシカン・ヘアーレス'},
 {'en': 'grey wolf', 'ja': 'シンリンオオカミ'},
 {'en': 'Alaskan tundra wolf', 'ja': '白いオオカミ'},
 {'en': 'red wolf or maned wolf', 'ja': 'レッドウルフ'},
 {'en': 'coyote', 'ja': 'コヨーテ'},
 {'en': 'dingo', 'ja': 'ディンゴ'},
 {'en': 'dhole', 'ja': 'ドール'},
 {'en': 'African wild dog', 'ja': 'リカオン'},
 {'en': 'hyena', 'ja': 'ハイエナ'},
 {'en': 'red fox', 'ja': 'アカギツネ'},
 {'en': 'kit fox', 'ja': 'キットキツネ'},
 {'en': 'Arctic fox', 'ja': 'ホッキョクギツネ'},
 {'en': 'grey fox', 'ja': '灰色のキツネ'},
 {'en': 'tabby cat', 'ja': 'タビー'},
 {'en': 'tiger cat', 'ja': '虎猫'},
 {'en': 'Persian cat', 'ja': 'ペルシャ猫'},
 {'en': 'Siamese cat', 'ja': 'シャム猫'},
 {'en': 'Egyptian Mau', 'ja': 'エジプトの猫'},
 {'en': 'cougar', 'ja': 'クーガー'},
 {'en': 'lynx', 'ja': 'オオヤマネコ'},
 {'en': 'leopard', 'ja': 'ヒョウ'},
 {'en': 'snow leopard', 'ja': 'ユキヒョウ'},
 {'en': 'jaguar', 'ja': 'ジャガー'},
 {'en': 'lion', 'ja': 'ライオン'},
 {'en': 'tiger', 'ja': '虎'},
 {'en': 'cheetah', 'ja': 'チーター'},
 {'en': 'brown bear', 'ja': 'ヒグマ'},
 {'en': 'American black bear', 'ja': 'アメリカクロクマ'},
 {'en': 'polar bear', 'ja': '氷のクマ'},
 {'en': 'sloth bear', 'ja': 'ナマケグマ'},
 {'en': 'mongoose', 'ja': 'マングース'},
 {'en': 'meerkat', 'ja': 'ミーアキャット'},
 {'en': 'tiger beetle', 'ja': 'ハンミョウ'},
 {'en': 'ladybug', 'ja': 'てんとう虫'},
 {'en': 'ground beetle', 'ja': 'グランドビートル'},
 {'en': 'longhorn beetle', 'ja': 'カミキリムシ'},
 {'en': 'leaf beetle', 'ja': 'ハムシ'},
 {'en': 'dung beetle', 'ja': 'フンコロガシ'},
 {'en': 'rhinoceros beetle', 'ja': 'サイハムシ'},
 {'en': 'weevil', 'ja': 'ゾウムシ'},
 {'en': 'fly', 'ja': 'ハエ'},
 {'en': 'bee', 'ja': '蜂'},
 {'en': 'ant', 'ja': '蟻'},
 {'en': 'grasshopper', 'ja': 'バッタ'},
 {'en': 'cricket insect', 'ja': 'クリケット'},
 {'en': 'stick insect', 'ja': '杖'},
 {'en': 'cockroach', 'ja': 'ゴキブリ'},
 {'en': 'praying mantis', 'ja': 'カマキリ'},
 {'en': 'cicada', 'ja': '蝉'},
 {'en': 'leafhopper', 'ja': 'ヨコバイ'},
 {'en': 'lacewing', 'ja': 'クサカゲロウ'},
 {'en': 'dragonfly', 'ja': 'トンボ'},
 {'en': 'damselfly', 'ja': 'イトトンボ'},
 {'en': 'red admiral butterfly', 'ja': '提督'},
 {'en': 'ringlet butterfly', 'ja': 'リングレット'},
 {'en': 'monarch butterfly', 'ja': '君主'},
 {'en': 'small white butterfly', 'ja': 'モンシロチョウ'},
 {'en': 'sulphur butterfly', 'ja': '硫黄蝶'},
 {'en': 'gossamer-winged butterfly', 'ja': 'シジミチョウ'},
 {'en': 'starfish', 'ja': 'ヒトデ'},
 {'en': 'sea urchin', 'ja': 'うに'},
 {'en': 'sea cucumber', 'ja': 'ナマコ'},
 {'en': 'cottontail rabbit', 'ja': '木のウサギ'},
 {'en': 'hare', 'ja': '野ウサギ'},
 {'en': 'Angora rabbit', 'ja': 'アンゴラ'},
 {'en': 'hamster', 'ja': 'ハムスター'},
 {'en': 'porcupine', 'ja': 'ヤマアラシ'},
 {'en': 'fox squirrel', 'ja': 'キツネリス'},
 {'en': 'marmot', 'ja': 'マーモット'},
 {'en': 'beaver', 'ja': 'ビーバー'},
 {'en': 'guinea pig', 'ja': 'モルモット'},
 {'en': 'common sorrel horse', 'ja': '栗色'},
 {'en': 'zebra', 'ja': 'シマウマ'},
 {'en': 'pig', 'ja': '豚'},
 {'en': 'wild boar', 'ja': 'イノシシ'},
 {'en': 'warthog', 'ja': 'イボイノシシ'},
 {'en': 'hippopotamus', 'ja': 'カバ'},
 {'en': 'ox', 'ja': '雄牛'},
 {'en': 'water buffalo', 'ja': '水牛'},
 {'en': 'bison', 'ja': 'バイソン'},
 {'en': 'ram (adult male sheep)', 'ja': 'ラム'},
 {'en': 'bighorn sheep', 'ja': 'ビッグホーン'},
 {'en': 'Alpine ibex', 'ja': 'アイベックス'},
 {'en': 'hartebeest', 'ja': 'ハーテビースト'},
 {'en': 'impala (antelope)', 'ja': 'インパラ'},
 {'en': 'gazelle', 'ja': 'ガゼル'},
 {'en': 'arabian camel', 'ja': 'アラビアラクダ'},
 {'en': 'llama', 'ja': 'ラマ'},
 {'en': 'weasel', 'ja': 'イタチ'},
 {'en': 'mink', 'ja': 'ミンク'},
 {'en': 'European polecat', 'ja': 'ケナガイタチ'},
 {'en': 'black-footed ferret', 'ja': 'クロアシイタチ'},
 {'en': 'otter', 'ja': 'カワウソ'},
 {'en': 'skunk', 'ja': 'スカンク'},
 {'en': 'badger', 'ja': '狸'},
 {'en': 'armadillo', 'ja': 'アルマジロ'},
 {'en': 'three-toed sloth', 'ja': 'ミユビナマケモノ'},
 {'en': 'orangutan', 'ja': 'オランウータン'},
 {'en': 'gorilla', 'ja': 'ゴリラ'},
 {'en': 'chimpanzee', 'ja': 'チンパンジー'},
 {'en': 'gibbon', 'ja': 'テナガザル'},
 {'en': 'siamang', 'ja': 'フクロテナガザル'},
 {'en': 'guenon', 'ja': 'オナガザル'},
 {'en': 'patas monkey', 'ja': 'パタス'},
 {'en': 'baboon', 'ja': 'ヒヒ'},
 {'en': 'macaque', 'ja': 'マカク'},
 {'en': 'langur', 'ja': 'ヤセザル'},
 {'en': 'black-and-white colobus', 'ja': 'コロブス属'},
 {'en': 'proboscis monkey', 'ja': 'テングザル'},
 {'en': 'marmoset', 'ja': 'マーモセット'},
 {'en': 'white-headed capuchin', 'ja': 'オマキザル'},
 {'en': 'howler monkey', 'ja': 'ホエザル'},
 {'en': 'titi monkey', 'ja': 'ティティ'},
 {'en': "Geoffroy's spider monkey", 'ja': 'クモザル'},
 {'en': 'common squirrel monkey', 'ja': 'リスザル'},
 {'en': 'ring-tailed lemur', 'ja': 'マダガスカル猫'},
 {'en': 'indri', 'ja': 'インドリ'},
 {'en': 'Asian elephant', 'ja': 'インドゾウ'},
 {'en': 'African bush elephant', 'ja': 'アフリカゾウ'},
 {'en': 'red panda', 'ja': 'レッサーパンダ'},
 {'en': 'giant panda', 'ja': 'ジャイアントパンダ'},
 {'en': 'snoek fish', 'ja': 'バラクータ'},
 {'en': 'eel', 'ja': 'ウナギ'},
 {'en': 'silver salmon', 'ja': 'ギンザケ'},
 {'en': 'rock beauty fish', 'ja': '岩の美しさ'},
 {'en': 'clownfish', 'ja': 'クマノミ'},
 {'en': 'sturgeon', 'ja': 'チョウザメ'},
 {'en': 'gar fish', 'ja': 'ガー'},
 {'en': 'lionfish', 'ja': 'ミノカサゴ'},
 {'en': 'pufferfish', 'ja': 'フグ'},
 {'en': 'abacus', 'ja': 'そろばん'},
 {'en': 'abaya', 'ja': 'アバヤ'},
 {'en': 'academic gown', 'ja': 'アカデミックガウン'},
 {'en': 'accordion', 'ja': 'アコーディオン'},
 {'en': 'acoustic guitar', 'ja': 'アコースティックギター'},
 {'en': 'aircraft carrier', 'ja': '空母'},
 {'en': 'airliner', 'ja': '旅客機'},
 {'en': 'airship', 'ja': '飛行船'},
 {'en': 'altar', 'ja': '祭壇'},
 {'en': 'ambulance', 'ja': '救急車'},
 {'en': 'amphibious vehicle', 'ja': '両生類'},
 {'en': 'analog clock', 'ja': 'アナログ時計'},
 {'en': 'apiary', 'ja': '養蜂場'},
 {'en': 'apron', 'ja': 'エプロン'},
 {'en': 'trash can', 'ja': 'ごみ入れ'},
 {'en': 'assault rifle', 'ja': 'アサルトライフル'},
 {'en': 'backpack', 'ja': 'バックパック'},
 {'en': 'bakery', 'ja': 'ベーカリー'},
 {'en': 'balance beam', 'ja': '平均台'},
 {'en': 'balloon', 'ja': 'バルーン'},
 {'en': 'ballpoint pen', 'ja': 'ボールペン'},
 {'en': 'Band-Aid', 'ja': 'バンドエイド'},
 {'en': 'banjo', 'ja': 'バンジョー'},
 {'en': 'baluster / handrail', 'ja': 'バニスター'},
 {'en': 'barbell', 'ja': 'バーベル'},
 {'en': 'barber chair', 'ja': '理髪店の椅子'},
 {'en': 'barbershop', 'ja': '理髪店'},
 {'en': 'barn', 'ja': '納屋'},
 {'en': 'barometer', 'ja': 'バロメーター'},
 {'en': 'barrel', 'ja': 'バレル'},
 {'en': 'wheelbarrow', 'ja': 'バロー'},
 {'en': 'baseball', 'ja': '野球'},
 {'en': 'basketball', 'ja': 'バスケットボール'},
 {'en': 'bassinet', 'ja': 'バシネット'},
 {'en': 'bassoon', 'ja': 'ファゴット'},
 {'en': 'swimming cap', 'ja': '水泳帽'},
 {'en': 'bath towel', 'ja': 'バスタオル'},
 {'en': 'bathtub', 'ja': 'バスタブ'},
 {'en': 'station wagon', 'ja': 'ビーチワゴン'},
 {'en': 'lighthouse', 'ja': 'ビーコン'},
 {'en': 'beaker', 'ja': 'ビーカー'},
 {'en': 'military hat (bearskin or shako)', 'ja': 'ベアスキン'},
 {'en': 'beer bottle', 'ja': 'ビール瓶'},
 {'en': 'beer glass', 'ja': 'ビールグラス'},
 {'en': 'bell tower', 'ja': 'ベルコート'},
 {'en': 'baby bib', 'ja': 'ビブ'},
 {'en': 'tandem bicycle', 'ja': '自転車'},
 {'en': 'bikini', 'ja': 'ビキニ'},
 {'en': 'ring binder', 'ja': 'バインダー'},
 {'en': 'binoculars', 'ja': '双眼鏡'},
 {'en': 'birdhouse', 'ja': '巣箱'},
 {'en': 'boathouse', 'ja': 'ボートハウス'},
 {'en': 'bobsleigh', 'ja': 'ボブスレー'},
 {'en': 'bolo tie', 'ja': 'ループタイ'},
 {'en': 'poke bonnet', 'ja': 'ボンネット'},
 {'en': 'bookcase', 'ja': '本棚'},
 {'en': 'bookstore', 'ja': '書店'},
 {'en': 'bottle cap', 'ja': '瓶のキャップ'},
 {'en': 'hunting bow', 'ja': '弓'},
 {'en': 'bow tie', 'ja': 'ちょうネクタイ'},
 {'en': 'brass memorial plaque', 'ja': '真鍮'},
 {'en': 'bra', 'ja': 'ブラジャー'},
 {'en': 'breakwater', 'ja': '防波堤'},
 {'en': 'breastplate', 'ja': '胸当て'},
 {'en': 'broom', 'ja': 'ほうき'},
 {'en': 'bucket', 'ja': 'バケツ'},
 {'en': 'buckle', 'ja': 'バックル'},
 {'en': 'bulletproof vest', 'ja': '防弾チョッキ'},
 {'en': 'high-speed train', 'ja': '新幹線'},
 {'en': 'butcher shop', 'ja': '精肉店'},
 {'en': 'taxicab', 'ja': 'タクシー'},
 {'en': 'cauldron', 'ja': '大釜'},
 {'en': 'candle', 'ja': 'キャンドル'},
 {'en': 'cannon', 'ja': '大砲'},
 {'en': 'canoe', 'ja': 'カヌー'},
 {'en': 'can opener', 'ja': '缶切り'},
 {'en': 'cardigan', 'ja': 'カーディガン'},
 {'en': 'car mirror', 'ja': '車のミラー'},
 {'en': 'carousel', 'ja': '回転木馬'},
 {'en': 'tool kit', 'ja': '大工のキット'},
 {'en': 'cardboard box / carton', 'ja': 'カートン'},
 {'en': 'car wheel', 'ja': '車のホイール'},
 {'en': 'automated teller machine', 'ja': '現金自動預け払い機'},
 {'en': 'cassette', 'ja': 'カセット'},
 {'en': 'cassette player', 'ja': 'カセット・プレーヤー'},
 {'en': 'castle', 'ja': '城'},
 {'en': 'catamaran', 'ja': 'カタマラン'},
 {'en': 'CD player', 'ja': 'CDプレーヤー'},
 {'en': 'cello', 'ja': 'チェロ'},
 {'en': 'mobile phone', 'ja': 'スマートフォン'},
 {'en': 'chain', 'ja': '鎖'},
 {'en': 'chain-link fence', 'ja': 'チェーンリンクフェンス'},
 {'en': 'chain mail', 'ja': 'チェーンメール'},
 {'en': 'chainsaw', 'ja': 'チェーンソー'},
 {'en': 'storage chest', 'ja': '胸'},
 {'en': 'chiffonier', 'ja': 'シフォニア'},
 {'en': 'bell or wind chime', 'ja': 'チャイム'},
 {'en': 'china cabinet', 'ja': '中国キャビネット'},
 {'en': 'Christmas stocking', 'ja': 'クリスマスの靴下'},
 {'en': 'church', 'ja': '教会'},
 {'en': 'movie theater', 'ja': '映画'},
 {'en': 'cleaver', 'ja': 'クリーバー'},
 {'en': 'cliff dwelling', 'ja': '崖の住居'},
 {'en': 'cloak', 'ja': 'マント'},
 {'en': 'clogs', 'ja': 'クロッグ'},
 {'en': 'cocktail shaker', 'ja': 'カクテルシェーカー'},
 {'en': 'coffee mug', 'ja': 'コーヒーマグ'},
 {'en': 'coffeemaker', 'ja': 'コーヒーポット'},
 {'en': 'spiral or coil', 'ja': 'コイル'},
 {'en': 'combination lock', 'ja': 'ダイヤル錠'},
 {'en': 'computer keyboard', 'ja': 'コンピュータのキーボード'},
 {'en': 'candy store', 'ja': '製菓'},
 {'en': 'container ship', 'ja': 'コンテナ船'},
 {'en': 'convertible', 'ja': 'コンバーチブル'},
 {'en': 'corkscrew', 'ja': 'コークスクリュー'},
 {'en': 'cornet', 'ja': 'コルネット'},
 {'en': 'cowboy boot', 'ja': 'カウボーイブーツ'},
 {'en': 'cowboy hat', 'ja': 'カウボーイハット'},
 {'en': 'cradle', 'ja': 'クレードル'},
 {'en': 'construction crane', 'ja': 'クレーン'},
 {'en': 'crash helmet', 'ja': 'クラッシュヘルメット'},
 {'en': 'crate', 'ja': '木箱'},
 {'en': 'infant bed', 'ja': 'ベビーベッド'},
 {'en': 'Crock Pot', 'ja': 'クロークポット'},
 {'en': 'croquet ball', 'ja': 'クロケットボール'},
 {'en': 'crutch', 'ja': '松葉杖'},
 {'en': 'cuirass', 'ja': '胸当て'},
 {'en': 'dam', 'ja': 'ダム'},
 {'en': 'desk', 'ja': '机'},
 {'en': 'desktop computer', 'ja': 'デスクトップコンピューター'},
 {'en': 'rotary dial telephone', 'ja': 'ダイヤル電話'},
 {'en': 'diaper', 'ja': 'おむつ'},
 {'en': 'digital clock', 'ja': 'デジタル時計'},
 {'en': 'digital watch', 'ja': 'デジタル腕時計'},
 {'en': 'dining table', 'ja': 'ダイニングテーブル'},
 {'en': 'dishcloth', 'ja': '意気地なし'},
 {'en': 'dishwasher', 'ja': '食器洗い機'},
 {'en': 'disc brake', 'ja': 'ディスクブレーキ'},
 {'en': 'dock', 'ja': 'ドック'},
 {'en': 'dog sled', 'ja': '犬ぞり'},
 {'en': 'dome', 'ja': 'ドーム'},
 {'en': 'doormat', 'ja': '玄関マット'},
 {'en': 'drilling rig', 'ja': '掘削基地'},
 {'en': 'drum', 'ja': 'ドラム'},
 {'en': 'drumstick', 'ja': 'ドラムスティック'},
 {'en': 'dumbbell', 'ja': 'ダンベル'},
 {'en': 'Dutch oven', 'ja': 'ダッチオーブン'},
 {'en': 'electric fan', 'ja': '扇風機'},
 {'en': 'electric guitar', 'ja': 'エレキギター'},
 {'en': 'electric locomotive', 'ja': '電気機関車'},
 {'en': 'entertainment center', 'ja': '娯楽施設'},
 {'en': 'envelope', 'ja': '封筒'},
 {'en': 'espresso machine', 'ja': 'エスプレッソマシーン'},
 {'en': 'face powder', 'ja': 'フェースパウダー'},
 {'en': 'feather boa', 'ja': 'フェザーボア'},
 {'en': 'filing cabinet', 'ja': 'ファイル'},
 {'en': 'fireboat', 'ja': '消防艇'},
 {'en': 'fire truck', 'ja': '消防車'},
 {'en': 'fire screen', 'ja': 'ファイアースクリーン'},
 {'en': 'flagpole', 'ja': '旗竿'},
 {'en': 'flute', 'ja': 'フルート'},
 {'en': 'folding chair', 'ja': '折り畳み式椅子'},
 {'en': 'football helmet', 'ja': 'フットボールヘルメット'},
 {'en': 'forklift', 'ja': 'フォークリフト'},
 {'en': 'fountain', 'ja': '噴水'},
 {'en': 'fountain pen', 'ja': '万年筆'},
 {'en': 'four-poster bed', 'ja': '四柱'},
 {'en': 'freight car', 'ja': '貨車'},
 {'en': 'French horn', 'ja': 'フレンチホルン'},
 {'en': 'frying pan', 'ja': 'フライパン'},
 {'en': 'fur coat', 'ja': '毛皮のコート'},
 {'en': 'garbage truck', 'ja': 'ごみ収集車'},
 {'en': 'gas mask or respirator', 'ja': 'ガスマスク'},
 {'en': 'gas pump', 'ja': 'ガソリンポンプ'},
 {'en': 'goblet', 'ja': 'ゴブレット'},
 {'en': 'go-kart', 'ja': 'ゴーカート'},
 {'en': 'golf ball', 'ja': 'ゴルフボール'},
 {'en': 'golf cart', 'ja': 'ゴルフカート'},
 {'en': 'gondola', 'ja': 'ゴンドラ'},
 {'en': 'gong', 'ja': 'ゴング'},
 {'en': 'gown', 'ja': 'ガウン'},
 {'en': 'grand piano', 'ja': 'グランドピアノ'},
 {'en': 'greenhouse', 'ja': '温室'},
 {'en': 'radiator grille', 'ja': 'グリル'},
 {'en': 'grocery store', 'ja': '食料品店'},
 {'en': 'guillotine', 'ja': 'ギロチン'},
 {'en': 'hair clip', 'ja': 'ヘアスライド'},
 {'en': 'hair spray', 'ja': 'ヘアスプレー'},
 {'en': 'half-track', 'ja': '半トラック'},
 {'en': 'hammer', 'ja': 'ハンマー'},
 {'en': 'hamper', 'ja': '妨げます'},
 {'en': 'hair dryer', 'ja': 'ハンドブロワー'},
 {'en': 'hand-held computer', 'ja': 'タブレット'},
 {'en': 'handkerchief', 'ja': 'ハンカチ'},
 {'en': 'hard disk drive', 'ja': 'ハードディスク'},
 {'en': 'harmonica', 'ja': 'ハーモニカ'},
 {'en': 'harp', 'ja': 'ハープ'},
 {'en': 'combine harvester', 'ja': 'ハーベスタ'},
 {'en': 'hatchet', 'ja': '斧'},
 {'en': 'holster', 'ja': 'ホルスター'},
 {'en': 'home theater', 'ja': 'ホームシアター'},
 {'en': 'honeycomb', 'ja': 'ハニカム'},
 {'en': 'hook', 'ja': 'フック'},
 {'en': 'hoop skirt', 'ja': 'フープスカート'},
 {'en': 'gymnastic horizontal bar', 'ja': '水平バー'},
 {'en': 'horse-drawn vehicle', 'ja': '馬車'},
 {'en': 'hourglass', 'ja': '砂時計'},
 {'en': 'iPod', 'ja': 'アイフォーン'},
 {'en': 'clothes iron', 'ja': '鉄'},
 {'en': 'carved pumpkin', 'ja': 'ジャックオーランタン'},
 {'en': 'jeans', 'ja': 'ジーンズ'},
 {'en': 'jeep', 'ja': 'ジープ'},
 {'en': 'T-shirt', 'ja': 'ジャージー'},
 {'en': 'jigsaw puzzle', 'ja': 'ジグソーパズル'},
 {'en': 'rickshaw', 'ja': '人力車'},
 {'en': 'joystick', 'ja': 'ジョイスティック'},
 {'en': 'kimono', 'ja': '着物'},
 {'en': 'knee pad', 'ja': '膝パッド'},
 {'en': 'knot', 'ja': '結び目'},
 {'en': 'lab coat', 'ja': '白衣'},
 {'en': 'ladle', 'ja': 'ひしゃく'},
 {'en': 'lampshade', 'ja': 'ランプのかさ'},
 {'en': 'laptop computer', 'ja': 'ノートパソコン'},
 {'en': 'lawn mower', 'ja': '芝刈り機'},
 {'en': 'lens cap', 'ja': 'レンズキャップ'},
 {'en': 'letter opener', 'ja': 'レターオープナー'},
 {'en': 'library', 'ja': 'ライブラリ'},
 {'en': 'lifeboat', 'ja': '救命ボート'},
 {'en': 'lighter', 'ja': 'ライター'},
 {'en': 'limousine', 'ja': 'リムジン'},
 {'en': 'ocean liner', 'ja': 'ライナー'},
 {'en': 'lipstick', 'ja': '口紅'},
 {'en': 'slip-on shoe', 'ja': 'ローファー'},
 {'en': 'lotion', 'ja': 'ローション'},
 {'en': 'music speaker', 'ja': 'スピーカー'},
 {'en': 'loupe magnifying glass', 'ja': 'ルーペ'},
 {'en': 'sawmill', 'ja': '製材所'},
 {'en': 'magnetic compass', 'ja': '磁気コンパス'},
 {'en': 'messenger bag', 'ja': '郵袋'},
 {'en': 'mailbox', 'ja': 'メールボックス'},
 {'en': 'tights', 'ja': 'マイヨ'},
 {'en': 'one-piece bathing suit', 'ja': 'マイヨ'},
 {'en': 'manhole cover', 'ja': 'マンホールの蓋'},
 {'en': 'maraca', 'ja': 'マラカス'},
 {'en': 'marimba', 'ja': 'マリンバ'},
 {'en': 'mask', 'ja': 'マスク'},
 {'en': 'matchstick', 'ja': 'マッチ棒'},
 {'en': 'maypole', 'ja': 'メイポール'},
 {'en': 'maze', 'ja': '迷路'},
 {'en': 'measuring cup', 'ja': '計量カップ'},
 {'en': 'medicine cabinet', 'ja': '薬箱'},
 {'en': 'megalith', 'ja': '巨石'},
 {'en': 'microphone', 'ja': 'マイク'},
 {'en': 'microwave oven', 'ja': 'マイクロ波'},
 {'en': 'military uniform', 'ja': '軍服'},
 {'en': 'milk can', 'ja': 'ミルク缶'},
 {'en': 'minibus', 'ja': 'ミニバス'},
 {'en': 'miniskirt', 'ja': 'ミニスカート'},
 {'en': 'minivan', 'ja': 'ミニバン'},
 {'en': 'missile', 'ja': 'ミサイル'},
 {'en': 'mitten', 'ja': 'ミトン'},
 {'en': 'mixing bowl', 'ja': 'ミキシングボウル'},
 {'en': 'mobile home', 'ja': '移動住宅'},
 {'en': 'ford model t', 'ja': 'モデルT'},
 {'en': 'modem', 'ja': 'モデム'},
 {'en': 'monastery', 'ja': '修道院'},
 {'en': 'monitor', 'ja': 'モニター'},
 {'en': 'moped', 'ja': 'モペット'},
 {'en': 'mortar and pestle', 'ja': 'モルタル'},
 {'en': 'graduation cap', 'ja': 'モルタルボード'},
 {'en': 'mosque', 'ja': 'モスク'},
 {'en': 'mosquito net', 'ja': '蚊帳'},
 {'en': 'vespa', 'ja': 'スクーター'},
 {'en': 'mountain bike', 'ja': 'マウンテンバイク'},
 {'en': 'tent', 'ja': '山のテント'},
 {'en': 'computer mouse', 'ja': 'マウス'},
 {'en': 'mousetrap', 'ja': 'ネズミ捕り'},
 {'en': 'moving van', 'ja': '引っ越しトラック'},
 {'en': 'muzzle', 'ja': '銃口'},
 {'en': 'metal nail', 'ja': 'ネイル'},
 {'en': 'neck brace', 'ja': 'ネックブレース'},
 {'en': 'necklace', 'ja': 'ネックレス'},
 {'en': 'baby pacifier', 'ja': '乳首'},
 {'en': 'notebook computer', 'ja': 'ノート'},
 {'en': 'obelisk', 'ja': 'オベリスク'},
 {'en': 'oboe', 'ja': 'オーボエ'},
 {'en': 'ocarina', 'ja': 'オカリナ'},
 {'en': 'odometer', 'ja': 'オドメーター'},
 {'en': 'oil filter', 'ja': 'オイルフィルター'},
 {'en': 'pipe organ', 'ja': '器官'},
 {'en': 'oscilloscope', 'ja': 'オシロスコープ'},
 {'en': 'overskirt', 'ja': 'オーバースカート'},
 {'en': 'bullock cart', 'ja': '牛車'},
 {'en': 'oxygen mask', 'ja': '酸素マスク'},
 {'en': 'product packet / packaging', 'ja': 'パケット'},
 {'en': 'paddle', 'ja': 'パドル'},
 {'en': 'paddle wheel', 'ja': 'パドルホイール'},
 {'en': 'padlock', 'ja': '南京錠'},
 {'en': 'paintbrush', 'ja': '絵筆'},
 {'en': 'pajamas', 'ja': 'パジャマ'},
 {'en': 'palace', 'ja': '宮殿'},
 {'en': 'pan flute', 'ja': 'パンパイプ'},
 {'en': 'paper towel', 'ja': 'ペーパータオル'},
 {'en': 'parachute', 'ja': 'パラシュート'},
 {'en': 'parallel bars', 'ja': '平行棒'},
 {'en': 'park bench', 'ja': '公園のベンチ'},
 {'en': 'parking meter', 'ja': 'パーキングメーター'},
 {'en': 'railroad car', 'ja': '乗用車'},
 {'en': 'patio', 'ja': 'パティオ'},
 {'en': 'payphone', 'ja': '有料電話'},
 {'en': 'pedestal', 'ja': '台座'},
 {'en': 'pencil case', 'ja': '筆箱'},
 {'en': 'pencil sharpener', 'ja': '鉛筆削り'},
 {'en': 'perfume', 'ja': '香水'},
 {'en': 'Petri dish', 'ja': 'ペトリ皿'},
 {'en': 'photocopier', 'ja': 'コピー機'},
 {'en': 'plectrum', 'ja': '選ぶ'},
 {'en': 'Pickelhaube', 'ja': 'スパイク付き鉄かぶと'},
 {'en': 'picket fence', 'ja': '杭柵'},
 {'en': 'pickup truck', 'ja': '拾う'},
 {'en': 'pier', 'ja': '桟橋'},
 {'en': 'piggy bank', 'ja': '貯金箱'},
 {'en': 'pill bottle', 'ja': '錠剤瓶'},
 {'en': 'pillow', 'ja': '枕'},
 {'en': 'ping-pong ball', 'ja': 'ピンポン球'},
 {'en': 'pinwheel', 'ja': '風車'},
 {'en': 'pirate ship', 'ja': '海賊'},
 {'en': 'drink pitcher', 'ja': 'ピッチャー'},
 {'en': 'block plane', 'ja': '飛行機'},
 {'en': 'planetarium', 'ja': 'プラネタリウム'},
 {'en': 'plastic bag', 'ja': 'ビニール袋'},
 {'en': 'plate rack', 'ja': '皿立て'},
 {'en': 'farm plow', 'ja': 'プラウ'},
 {'en': 'plunger', 'ja': 'プランジャー'},
 {'en': 'Polaroid camera', 'ja': 'ポラロイドカメラ'},
 {'en': 'pole', 'ja': 'ポール'},
 {'en': 'police van', 'ja': '警察車'},
 {'en': 'poncho', 'ja': 'ポンチョ'},
 {'en': 'pool table', 'ja': 'ビリヤード台'},
 {'en': 'soda bottle', 'ja': 'ポップ・ボトル'},
 {'en': 'plant pot', 'ja': 'ポット'},
 {'en': "potter's wheel", 'ja': 'ろくろ'},
 {'en': 'power drill', 'ja': 'パワードリル'},
 {'en': 'prayer rug', 'ja': '礼拝用敷物'},
 {'en': 'printer', 'ja': 'プリンタ'},
 {'en': 'prison', 'ja': '刑務所'},
 {'en': 'missile', 'ja': '発射体'},
 {'en': 'projector', 'ja': 'プロジェクター'},
 {'en': 'hockey puck', 'ja': 'パック'},
 {'en': 'punching bag', 'ja': 'サンドバッグ'},
 {'en': 'purse', 'ja': '財布'},
 {'en': 'quill', 'ja': 'クイル'},
 {'en': 'quilt', 'ja': 'キルト'},
 {'en': 'race car', 'ja': 'レーサー'},
 {'en': 'racket', 'ja': 'ラケット'},
 {'en': 'radiator', 'ja': 'ラジエーター'},
 {'en': 'radio', 'ja': '無線'},
 {'en': 'radio telescope', 'ja': '電波望遠鏡'},
 {'en': 'rain barrel', 'ja': '天水桶'},
 {'en': 'recreational vehicle', 'ja': 'RV車'},
 {'en': 'fishing casting reel', 'ja': 'リール'},
 {'en': 'reflex camera', 'ja': 'レフレックスカメラ'},
 {'en': 'refrigerator', 'ja': '冷蔵庫'},
 {'en': 'remote control', 'ja': 'リモコン'},
 {'en': 'restaurant', 'ja': 'レストラン'},
 {'en': 'revolver', 'ja': 'リボルバー'},
 {'en': 'rifle', 'ja': 'ライフル'},
 {'en': 'rocking chair', 'ja': 'ロッキングチェア'},
 {'en': 'rotisserie', 'ja': '焼肉料理店'},
 {'en': 'eraser', 'ja': '消しゴム'},
 {'en': 'rugby ball', 'ja': 'ラグビーボール'},
 {'en': 'ruler measuring stick', 'ja': 'ルール'},
 {'en': 'sneaker', 'ja': 'ランニングシューズ'},
 {'en': 'safe', 'ja': '安全'},
 {'en': 'safety pin', 'ja': '安全ピン'},
 {'en': 'salt shaker', 'ja': '塩の入れ物'},
 {'en': 'sandal', 'ja': 'サンダル'},
 {'en': 'sarong', 'ja': 'サロン'},
 {'en': 'saxophone', 'ja': 'サックス'},
 {'en': 'scabbard', 'ja': '鞘'},
 {'en': 'weighing scale', 'ja': '規模'},
 {'en': 'school bus', 'ja': 'スクールバス'},
 {'en': 'schooner', 'ja': 'スクーナー'},
 {'en': 'scoreboard', 'ja': 'スコアボード'},
 {'en': 'CRT monitor', 'ja': '画面'},
 {'en': 'screw', 'ja': 'スクリュー'},
 {'en': 'screwdriver', 'ja': 'ドライバー'},
 {'en': 'seat belt', 'ja': 'シートベルト'},
 {'en': 'sewing machine', 'ja': 'ミシン'},
 {'en': 'shield', 'ja': 'シールド'},
 {'en': 'shoe store', 'ja': '靴屋'},
 {'en': 'shoji screen / room divider', 'ja': '障子'},
 {'en': 'shopping basket', 'ja': '買い物かご'},
 {'en': 'shopping cart', 'ja': 'ショッピングカート'},
 {'en': 'shovel', 'ja': 'シャベル'},
 {'en': 'shower cap', 'ja': 'シャワーキャップ'},
 {'en': 'shower curtain', 'ja': 'シャワーカーテン'},
 {'en': 'ski', 'ja': 'スキー'},
 {'en': 'balaclava ski mask', 'ja': 'スキーマスク'},
 {'en': 'sleeping bag', 'ja': '寝袋'},
 {'en': 'slide rule', 'ja': '計算尺'},
 {'en': 'sliding door', 'ja': '引き戸'},
 {'en': 'slot machine', 'ja': 'スロット'},
 {'en': 'snorkel', 'ja': 'スノーケル'},
 {'en': 'snowmobile', 'ja': 'スノーモービル'},
 {'en': 'snowplow', 'ja': '除雪機'},
 {'en': 'soap dispenser', 'ja': 'ソープディスペンサー'},
 {'en': 'soccer ball', 'ja': 'サッカーボール'},
 {'en': 'sock', 'ja': '靴下'},
 {'en': 'solar thermal collector', 'ja': '太陽の皿'},
 {'en': 'sombrero', 'ja': 'ソンブレロ'},
 {'en': 'soup bowl', 'ja': 'スープ皿'},
 {'en': 'keyboard space bar', 'ja': 'スペースキー'},
 {'en': 'space heater', 'ja': 'スペースヒーター'},
 {'en': 'space shuttle', 'ja': 'スペースシャトル'},
 {'en': 'spatula', 'ja': 'へら'},
 {'en': 'motorboat', 'ja': 'スピードボート'},
 {'en': 'spider web', 'ja': 'クモの巣'},
 {'en': 'spindle', 'ja': 'スピンドル'},
 {'en': 'sports car', 'ja': 'スポーツカー'},
 {'en': 'spotlight', 'ja': 'スポットライト'},
 {'en': 'stage', 'ja': 'ステージ'},
 {'en': 'steam locomotive', 'ja': '蒸気機関車'},
 {'en': 'through arch bridge', 'ja': '鋼アーチ橋'},
 {'en': 'steel drum', 'ja': 'スチールドラム'},
 {'en': 'stethoscope', 'ja': '聴診器'},
 {'en': 'scarf', 'ja': 'ストール'},
 {'en': 'stone wall', 'ja': '石垣'},
 {'en': 'stopwatch', 'ja': 'ストップウォッチ'},
 {'en': 'stove', 'ja': 'レンジ'},
 {'en': 'strainer', 'ja': 'ストレーナー'},
 {'en': 'tram', 'ja': '路面電車'},
 {'en': 'stretcher', 'ja': 'ストレッチャー'},
 {'en': 'couch', 'ja': 'スタジオソファ'},
 {'en': 'stupa', 'ja': '仏舎利塔'},
 {'en': 'submarine', 'ja': '潜水艦'},
 {'en': 'suit', 'ja': 'スーツ'},
 {'en': 'sundial', 'ja': '日時計'},
 {'en': 'sunglasses', 'ja': 'サングラス'},
 {'en': 'sunglasses', 'ja': 'サングラス'},
 {'en': 'sunscreen', 'ja': '日焼け止め剤'},
 {'en': 'suspension bridge', 'ja': 'つり橋'},
 {'en': 'mop', 'ja': '綿棒'},
 {'en': 'sweatshirt', 'ja': 'トレーナー'},
 {'en': 'swim trunks / shorts', 'ja': '海パン'},
 {'en': 'swing', 'ja': 'スイング'},
 {'en': 'electrical switch', 'ja': 'スイッチ'},
 {'en': 'syringe', 'ja': '注射器'},
 {'en': 'table lamp', 'ja': '電気スタンド'},
 {'en': 'tank', 'ja': 'タンク'},
 {'en': 'tape player', 'ja': 'テーププレーヤー'},
 {'en': 'teapot', 'ja': 'ティーポット'},
 {'en': 'teddy bear', 'ja': 'テディ'},
 {'en': 'television', 'ja': 'テレビ'},
 {'en': 'tennis ball', 'ja': 'テニスボール'},
 {'en': 'thatched roof', 'ja': 'サッチ'},
 {'en': 'front curtain', 'ja': '劇場のカーテン'},
 {'en': 'thimble', 'ja': '指ぬき'},
 {'en': 'threshing machine', 'ja': '脱穀機'},
 {'en': 'throne', 'ja': '王位'},
 {'en': 'tile roof', 'ja': '瓦屋根'},
 {'en': 'toaster', 'ja': 'トースター'},
 {'en': 'tobacco shop', 'ja': 'タバコ屋'},
 {'en': 'toilet seat', 'ja': '便座'},
 {'en': 'torch', 'ja': 'トーチ'},
 {'en': 'totem pole', 'ja': 'トーテムポール'},
 {'en': 'tow truck', 'ja': 'レッカー車'},
 {'en': 'toy store', 'ja': '玩具屋'},
 {'en': 'tractor', 'ja': 'トラクター'},
 {'en': 'semi-trailer truck', 'ja': 'トレーラートラック'},
 {'en': 'tray', 'ja': 'トレイ'},
 {'en': 'trench coat', 'ja': 'トレンチコート'},
 {'en': 'tricycle', 'ja': '三輪車'},
 {'en': 'trimaran', 'ja': '三胴船'},
 {'en': 'tripod', 'ja': '三脚'},
 {'en': 'triumphal arch', 'ja': '凱旋門'},
 {'en': 'trolleybus', 'ja': 'トロリーバス'},
 {'en': 'trombone', 'ja': 'トロンボーン'},
 {'en': 'hot tub', 'ja': 'バスタブ'},
 {'en': 'turnstile', 'ja': '回転ドア'},
 {'en': 'typewriter keyboard', 'ja': 'タイプライターのキーボード'},
 {'en': 'umbrella', 'ja': '傘'},
 {'en': 'unicycle', 'ja': '一輪車'},
 {'en': 'upright piano', 'ja': '直立'},
 {'en': 'vacuum cleaner', 'ja': '真空'},
 {'en': 'vase', 'ja': '花瓶'},
 {'en': 'vaulted or arched ceiling', 'ja': 'ボールト'},
 {'en': 'velvet fabric', 'ja': 'ベルベット'},
 {'en': 'vending machine', 'ja': '自動販売機'},
 {'en': 'vestment', 'ja': '祭服'},
 {'en': 'viaduct', 'ja': '高架橋'},
 {'en': 'violin', 'ja': 'バイオリン'},
 {'en': 'volleyball', 'ja': 'バレーボール'},
 {'en': 'waffle iron', 'ja': 'ワッフル焼き型'},
 {'en': 'wall clock', 'ja': '壁時計'},
 {'en': 'wallet', 'ja': '財布'},
 {'en': 'wardrobe', 'ja': 'ワードローブ'},
 {'en': 'military aircraft', 'ja': '戦闘機'},
 {'en': 'sink', 'ja': '洗面器'},
 {'en': 'washing machine', 'ja': 'ワッシャー'},
 {'en': 'water bottle', 'ja': '水筒'},
 {'en': 'water jug', 'ja': '水差し'},
 {'en': 'water tower', 'ja': '給水塔'},
 {'en': 'whiskey jug', 'ja': 'ウイスキージャグ'},
 {'en': 'whistle', 'ja': 'ホイッスル'},
 {'en': 'hair wig', 'ja': 'かつら'},
 {'en': 'window screen', 'ja': '窓網戸'},
 {'en': 'window shade', 'ja': 'ブラインド'},
 {'en': 'Windsor tie', 'ja': 'ウィンザーネクタイ'},
 {'en': 'wine bottle', 'ja': 'ワインボトル'},
 {'en': 'airplane wing', 'ja': '翼'},
 {'en': 'wok', 'ja': '中華鍋'},
 {'en': 'wooden spoon', 'ja': '木製スプーン'},
 {'en': 'wool', 'ja': 'ウール'},
 {'en': 'split-rail fence', 'ja': 'ワームフェンス'},
 {'en': 'shipwreck', 'ja': '難破船'},
 {'en': 'sailboat', 'ja': 'ヨール'},
 {'en': 'yurt', 'ja': 'パオ'},
 {'en': 'website', 'ja': 'サイト'},
 {'en': 'comic book', 'ja': 'コミックブック'},
 {'en': 'crossword', 'ja': 'クロスワードパズル'},
 {'en': 'traffic or street sign', 'ja': '道路標識'},
 {'en': 'traffic light', 'ja': '交通信号灯'},
 {'en': 'dust jacket', 'ja': 'ブックカバー'},
 {'en': 'menu', 'ja': 'メニュー'},
 {'en': 'plate', 'ja': 'プレート'},
 {'en': 'guacamole', 'ja': 'グアカモーレ'},
 {'en': 'consomme', 'ja': 'コンソメ'},
 {'en': 'hot pot', 'ja': 'ホットポット'},
 {'en': 'trifle', 'ja': 'パフェ'},
 {'en': 'ice cream', 'ja': 'アイスクリーム'},
 {'en': 'popsicle', 'ja': 'アイスキャンディー'},
 {'en': 'baguette', 'ja': 'フランスパン'},
 {'en': 'bagel', 'ja': 'ベーグル'},
 {'en': 'pretzel', 'ja': 'プレッツェル'},
 {'en': 'cheeseburger', 'ja': 'チーズバーガー'},
 {'en': 'hot dog', 'ja': 'ホットドッグ'},
 {'en': 'mashed potatoes', 'ja': 'マッシュポテト'},
 {'en': 'cabbage', 'ja': 'キャベツ'},
 {'en': 'broccoli', 'ja': 'ブロッコリー'},
 {'en': 'cauliflower', 'ja': 'カリフラワー'},
 {'en': 'zucchini', 'ja': 'ズッキーニ'},
 {'en': 'spaghetti squash', 'ja': 'そうめんかぼちゃ'},
 {'en': 'acorn squash', 'ja': 'ドングリかぼちゃ'},
 {'en': 'butternut squash', 'ja': 'カボチャ'},
 {'en': 'cucumber', 'ja': 'キュウリ'},
 {'en': 'artichoke', 'ja': 'アーティチョーク'},
 {'en': 'bell pepper', 'ja': 'ピーマン'},
 {'en': 'cardoon', 'ja': 'カルドン'},
 {'en': 'mushroom', 'ja': 'キノコ'},
 {'en': 'Granny Smith apple', 'ja': 'リンゴ'},
 {'en': 'strawberry', 'ja': 'イチゴ'},
 {'en': 'orange', 'ja': 'オレンジ'},
 {'en': 'lemon', 'ja': 'レモン'},
 {'en': 'fig', 'ja': 'イチジク'},
 {'en': 'pineapple', 'ja': 'パイナップル'},
 {'en': 'banana', 'ja': 'バナナ'},
 {'en': 'jackfruit', 'ja': 'パラミツ'},
 {'en': 'cherimoya (custard apple)', 'ja': 'カスタードアップル'},
 {'en': 'pomegranate', 'ja': 'ザクロ'},
 {'en': 'hay', 'ja': '干し草'},
 {'en': 'carbonara', 'ja': 'カルボナーラ'},
 {'en': 'chocolate syrup', 'ja': 'チョコレートソース'},
 {'en': 'dough', 'ja': 'パン生地'},
 {'en': 'meatloaf', 'ja': 'ミートローフ'},
 {'en': 'pizza', 'ja': 'ピザ'},
 {'en': 'pot pie', 'ja': 'ポットパイ'},
 {'en': 'burrito', 'ja': 'ブリトー'},
 {'en': 'red wine', 'ja': '赤ワイン'},
 {'en': 'espresso', 'ja': 'エスプレッソ'},
 {'en': 'tea cup', 'ja': 'カップ'},
 {'en': 'eggnog', 'ja': 'エッグノッグ'},
 {'en': 'mountain', 'ja': 'アルプス'},
 {'en': 'bubble', 'ja': 'バブル'},
 {'en': 'cliff', 'ja': '崖'},
 {'en': 'coral reef', 'ja': 'サンゴ礁'},
 {'en': 'geyser', 'ja': '間欠泉'},
 {'en': 'lakeshore', 'ja': '湖畔'},
 {'en': 'promontory', 'ja': '岬'},
 {'en': 'sandbar', 'ja': '砂州'},
 {'en': 'beach', 'ja': '海岸'},
 {'en': 'valley', 'ja': '谷'},
 {'en': 'volcano', 'ja': '火山'},
 {'en': 'baseball player', 'ja': '野球選手'},
 {'en': 'bridegroom', 'ja': '新郎'},
 {'en': 'scuba diver', 'ja': 'スキューバダイバー'},
 {'en': 'rapeseed', 'ja': '菜種'},
 {'en': 'daisy', 'ja': 'デイジー'},
 {'en': "yellow lady's slipper", 'ja': '蘭'},
 {'en': 'corn', 'ja': 'トウモロコシ'},
 {'en': 'acorn', 'ja': 'ドングリ'},
 {'en': 'rose hip', 'ja': 'ヒップ'},
 {'en': 'horse chestnut seed', 'ja': 'トチノキ'},
 {'en': 'coral fungus', 'ja': 'サンゴ菌'},
 {'en': 'agaric', 'ja': 'ハラタケ'},
 {'en': 'gyromitra', 'ja': 'シャグマアミガサタケ'},
 {'en': 'stinkhorn mushroom', 'ja': 'スッポンタケ'},
 {'en': 'earth star fungus', 'ja': 'ハラタケ'},
 {'en': 'hen of the woods mushroom', 'ja': '舞茸'},
 {'en': 'bolete', 'ja': 'きのこ'},
 {'en': 'corn cob', 'ja': '耳'},
 {'en': 'toilet paper', 'ja': 'トイレットペーパー'}]


imagenet_templates = [{'en': 'a bad photo of a {}.', 'ja': '{}の悪い写真'},
 {'en': 'a photo of many {}.', 'ja': '多くの{}の写真'},
 {'en': 'a sculpture of a {}.', 'ja': '{}の彫刻'},
 {'en': 'a photo of the hard to see {}.', 'ja': '見づらい{}の写真'},
 {'en': 'a low resolution photo of the {}.', 'ja': '{}の低解像度写真'},
 {'en': 'a rendering of a {}.', 'ja': '{}のレンダリング'},
 {'en': 'graffiti of a {}.', 'ja': '{}の落書き'},
 {'en': 'a cropped photo of the {}.', 'ja': '{}のトリミング写真'},
 {'en': 'a tattoo of a {}.', 'ja': '{}のタトゥー'},
 {'en': 'the embroidered {}.', 'ja': '刺繍された{}'},
 {'en': 'a bright photo of a {}.', 'ja': '{}の明るい写真'},
 {'en': 'a photo of a clean {}.', 'ja': 'きれいな{}の写真'},
 {'en': 'a photo of a dirty {}.', 'ja': '汚れた{}の写真'},
 {'en': 'a dark photo of the {}.', 'ja': '{}の暗い写真'},
 {'en': 'a drawing of a {}.', 'ja': '{}の絵'},
 {'en': 'a photo of my {}.', 'ja': '私の{}の写真'},
 {'en': 'the plastic {}.', 'ja': 'プラスチック製の{}'},
 {'en': 'a photo of the cool {}.', 'ja': 'かっこいい{}の写真'},
 {'en': 'a close-up photo of a {}.', 'ja': '{}のクローズアップ写真'},
 {'en': 'a black and white photo of the {}.', 'ja': '{}の白黒写真'},
 {'en': 'a pixelated photo of the {}.', 'ja': '{}のピクセル写真'},
 {'en': 'a jpeg corrupted photo of a {}.', 'ja': 'jpegで加工した{}の写真'},
 {'en': 'a blurry photo of the {}.', 'ja': '{}のぼやけた写真'},
 {'en': 'a photo of the {}.', 'ja': '{}の写真'},
 {'en': 'a good photo of the {}.', 'ja': '{}の良い写真'},
 {'en': 'a {} in a video game.', 'ja': 'ゲームに登場する{}'},
 {'en': 'the origami {}.', 'ja': '折り紙で作った{}'},
 {'en': 'a sketch of a {}.', 'ja': '{}のスケッチ'},
 {'en': 'the toy {}.', 'ja': 'おもちゃの{}'},
 {'en': 'a rendition of the {}.', 'ja': '{}の演出'},
 {'en': 'a photo of a large {}.', 'ja': '大きな{}の写真'},
 {'en': 'a photo of a nice {}.', 'ja': '素敵な{}の写真'},
 {'en': 'a photo of a weird {}.', 'ja': '奇妙な{}の写真'},
 {'en': 'a cartoon {}.', 'ja': '漫画の{}'},
 {'en': 'art of a {}.', 'ja': '{}の芸術'},
 {'en': 'a plushie {}.', 'ja': '{}のぬいぐるみ'},
 {'en': 'a photo of the small {}.', 'ja': '小さな{}の写真'},]




